# CHECK GIVEN STRINGS ARE ANAGRAMS OR NOT
# ANAGRAMS - BOTH STRINGS HAVE SIMILAR CHARACTERS BUT NOT IN SAME ORDER
# LISTEN - SILENT , FIRED - FRIED , TIANGLE - INTEGRAL
s1 = input('ENTER FIRST STRING :')
s2 = input('ENTER SECOND STRING :')
if sorted(s1) == sorted(s2):
    print('BOTH ARE ANAGARAMS')
else:
    print('BOTH ARE NOT ANAGRAMS')
